### ISSUE TITLE
Themen Spezifikation

### ISSUE THREAD

**Issue by DrTurtle** [Fuenfgeld/2022TeamADataManagementBC#1]

**Comment by lukasbu123** [comment]
Uns ist noch etwas Unklar, wie weit unser Thema sich erstreckt? 
1. Bezieht es sich speziell auf die Verwendung und Erstellung von Metadaten, oder 
2. Eher Allgemeiner und wie werden Daten im Bezug auf  das OASI-Modell aufgebaut.

**Comment by Fuenfgeld** [comment]
In dem Projekt soll es darum gehen die verschiedenen Typen von Metadaten zu erklären. Das OAIS Modell soll nicht erklärt werden. Der OAIS Standart gibt nur an welche Metadaten Typen es gibt und wie diese zusammenhängen.

**Comment by Fuenfgeld** [comment]
Ich stelle mir das so vor das ihr eine fiktive studie durchführt (zB basierend auf den Datensätze aus scikit learn) und dabei die Metadaten erhebt.

**Comment by lukasbu123** [comment]
> Ich stelle mir das so vor das ihr eine fiktive studie durchführt (zB basierend auf den Datensätze aus scikit learn) und dabei die Metadaten erhebt.

Danke, damit hat sich die Frage geklärt.
